config/routes.rb
Rails.application.routes.draw do
  root "feeds#show"
  devise_for :users

  # users routes
  resources :users, :only => [:show, :edit, :update, :index] do
    member do
      get 'followers'
      get 'following'
    end
  end

  # devise routes'


  # Post routes'
  resources :posts

  resources :tags
  resources :followings, :likes, :comments
  get "/feed", to: "feeds#show"
  get "/explore", to: "feeds#explore"
  get "/liked_posts", to: "users#liked_posts"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]
  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  has_many :active_followings, class_name: "Following", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_followings, class_name: "Following", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_followings, source: :followed
  has_many :followers, through: :passive_followings, source: :follower

  #validations
  validates :first_name, :surname, :username, :email, presence: true
  validates :email, :username, uniqueness: { case_sensitive: false, message: "%{value} already taken." }
  validates :username, length: { in: 3..25}
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }



  #devise username setup
  attr_writer :login
  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  elsif conditions.has_key?(:username) || conditions.has_key?(:email)
    conditions[:email].downcase! if conditions[:email]
    where(conditions.to_h).first
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.where(first_name: params[:name])

  end

  def show
    @user= User.find(params[:id])
    @followers=@user.followers.length
    @following=@user.following.length
    @posts=@user.posts
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def home
    @user=current_user
    @followers=@user.followers.length
    @following=@user.following.length
    @posts=@user.posts
    @post=@user.posts.build
    @post.tags.build
    redirect_to @user
  end


  def followers
    @user= User.find(params[:id])
    @users=@user.followers
  end

  def following
    @user= User.find(params[:id])
    @users=@user.following
  end

  def liked_posts
    @posts=current_user.liked_posts
  end
  private

  def user_params
    params.require(:user).permit(:avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, @user.username) %>
<div class="form-container">
  <h2 id="update-avatar">Update Avatar</h2>
  <div id="avatar-box">
    <% if !@user.avatar.file.nil? %>
      <%= image_tag @user.avatar.main.url, class: :avatar  %>
    <% else %>
      <%= image_tag "user.png", class: :avatar  %>
    <% end %>
  </div>
  <%= form_for((@user), :html =>{:multipart => true})  do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <div class="actions">
      <%= f.file_field :avatar, required: :required %>
    </div>
    <div class="actions" id="upload">
      <%= f.submit "Upload", class: :submit %>
    </div>
  <% end %>
</div>

app/views/users/followers.html.erb
<% provide(:title, @user.username) %>
<div class="follows-list">
  <h2>Followers</h2>

    <% if @users.count > 0  %>
      <% @users.each do |user|  %>
      <div class="f-user-box">
        <div class="f-avatar-box">
          <% if !user.avatar.file.nil? %>
              <%= image_tag(user.avatar.main.url, class: :user_image) %>
            <% else %>
              <%= image_tag("user.png", class: :user_image) %>
          <% end %>
        </div>

        <div class="f-details-box">
          <%= link_to user_path(user) do %>
            <p id="username"><%= user.username %></p>
            <p id="name"><%= "#{user.first_name} #{user.surname}" %></p>
          <% end %>
        </div>

        <div class="f-follow-box" id="follower_<%= user.id %>">
          <% if current_user.following.include?(user) %>
            <%= render "partials/hun_following_form", user: user %>
          <% else  %>
            <%= render "partials/hfollowing_form", user: user %>
          <% end %>
        </div>

      </div>
    <% end %>
    <% else %>
      <div id="first-v-div">
        <p id="first-v">Users who follow you will appear here</p>
      </div>
    <% end %>

</div>

app/views/users/following.html.erb
<% provide(:title, @user.username) %>
<div class="follows-list">
  <h2>Following</h2>

  <% if @users.length > 0  %>
    <% @users.each do |user|  %>
    <div class="f-user-box">
      <div class="f-avatar-box">
        <% if !user.avatar.file.nil? %>
            <%= image_tag(user.avatar.main.url, class: :user_image) %>
          <% else %>
            <%= image_tag("user.png", class: :user_image) %>
        <% end %>
      </div>

      <div class="f-details-box">
        <%= link_to user_path(user) do %>
          <p id="username"><%= user.username %></p>
          <p id="name"><%= "#{user.first_name} #{user.surname}" %></p>
        <% end %>
      </div>

      <div class="f-follow-box" id="follower_<%= user.id %>">
        <% if current_user.following.include?(user) %>
          <%= render "partials/hun_following_form", user: user %>
        <% else  %>
          <%= render "partials/hfollowing_form", user: user %>
        <% end %>
      </div>

  </div>
  <% end %>
  <% else %>
    <div id="first-v-div">
      <p id="first-v">Users you follow will appear here</p>
    </div>
  <% end %>

</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<div class="follows-list">
  <h2>Users</h2>


      <% @users.each do |user|  %>
      <div class="f-user-box">
        <div class="f-avatar-box">
          <% if !user.avatar.file.nil? %>
            <%= link_to (image_tag user.avatar.main.url, class: :avatar), user_path(user)  %>
          <% else %>
            <%= link_to (image_tag "user.png", class: :avatar), user_path(user)  %>
          <% end %>
        </div>

        <div class="f-details-box">
          <%= link_to user_path(user) do %>
            <p id="username"><%= user.username %></p>
            <p id="name"><%= "#{user.first_name} #{user.surname}" %></p>
          <% end %>
        </div>

        <% if current_user != user %>
          <div class="f-follow-box" id="follower_<%= user.id %>">
            <% if current_user.following.include?(user) %>
              <%= render "partials/hun_following_form", user: user %>
            <% else  %>
              <%= render "partials/hfollowing_form", user: user %>
            <% end %>
          </div>
        <% end %>

      </div>
    <% end %>

</div>

app/views/users/liked_posts.html.erb
<% provide(:title, current_user.username) %>
<h1>#Likes</h1>
<% if @posts.count > 0 %>
  <%= render "partials/posts" %>
<% else %>
  <p id="first-v">Posts that you like will appear here</p>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="poster-info">
  <div class="user-avatar">
    <div id="avatar-box">
        <% if @user === current_user %>
          <% if !@user.avatar.file.nil? %>
            <%= link_to (image_tag @user.avatar.main.url, class: :avatar), edit_user_path(current_user) %>
          <% else %>
            <%= link_to (image_tag "user.png", class: :avatar), edit_user_path(current_user) %>
          <% end %>
          <p id="ed-icon"><%= link_to "Edit Icon", edit_user_path(current_user) %></p>
        <% else %>
          <% if !@user.avatar.file.nil? %>
            <%= image_tag @user.avatar.main.url, class: :avatar %>
          <% else %>
            <%= image_tag "user.png", class: :avatar  %>
          <% end %>
        <% end %>

    </div>

  </div>
  <div class="user-links">
    <div id="profile-username">
      <p><%= @user.username %></p>

    <%= link_to "Edit Profile", edit_user_registration_path(@user) if @user === current_user %>
    <%= link_to "logout", destroy_user_session_path, method: :delete  if @user === current_user %>
      <% if @user != current_user %>
      <div id="follow_form">
          <% if !followed_by_visitor?(@user.followers) %>
            <%= render "partials/following_form" %>
            <% else  %>
            <%= render "partials/un_following_form" %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div id="follows">
      <p id="p-length"><%= pluralize(@posts.length,  "Post") %></p>
      <%= link_to pluralize(@user.followers.count, "Follower"), followers_user_path(@user), id: :no_followers %>
      <%= link_to pluralize(@user.following.count, "Following"), following_user_path(@user) %>
      <p><%= "#{@user.first_name} #{@user.surname} " %></p>
    </div>
  </div>

</div>


<%= render "partials/posts" %>