config/routes.rb
Rails.application.routes.draw do
  root "feeds#show"
  devise_for :users

  # users routes
  resources :users, :only => [:show, :edit, :update, :index] do
    member do
      get 'followers'
      get 'following'
    end
  end

  # devise routes'


  # Post routes'
  resources :posts

  resources :tags
  resources :followings, :likes, :comments
  get "/feed", to: "feeds#show"
  get "/explore", to: "feeds#explore"
  get "/liked_posts", to: "users#liked_posts"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  #validations
  validates :text, presence: true,  length: { maximum: 250 }
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  mount_uploader :post_image, PostUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :likers, :through => :likes, :source => :user
  has_many :taggings, dependent: :destroy
  has_many :tags, :through => :taggings, :source => :tag
  accepts_nested_attributes_for :tags

 #image uploads


  #validations
  validates :caption, length: { maximum: 250 }
  validates :post_image, :caption, presence: true

end

app/models/tag.rb
class Tag < ApplicationRecord
  before_validation :lowercase, :hashit
  has_many :taggings
  has_many :posts, :through => :taggings

  validates :hashtag, presence: true, uniqueness: true
  #regex for tags

  private
  #formatters
  def lowercase
    self.hashtag= self.hashtag.downcase
  end

  def hashit
    self.hashtag="#"+ self.hashtag if self.hashtag[0]!="#"
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]
  mount_uploader :avatar, AvatarUploader
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  has_many :active_followings, class_name: "Following", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_followings, class_name: "Following", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_followings, source: :followed
  has_many :followers, through: :passive_followings, source: :follower

  #validations
  validates :first_name, :surname, :username, :email, presence: true
  validates :email, :username, uniqueness: { case_sensitive: false, message: "%{value} already taken." }
  validates :username, length: { in: 3..25}
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }



  #devise username setup
  attr_writer :login
  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  elsif conditions.has_key?(:username) || conditions.has_key?(:email)
    conditions[:email].downcase! if conditions[:email]
    where(conditions.to_h).first
  end
end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def show
     @following_ids=[]
     current_user.following.each do |f|
      @following_ids<< f.id
     end
     @following_ids<<current_user.id
     @following_ids=@following_ids.join(", ")
     @posts=Post.where("user_id IN (#{@following_ids})")
 end

 def explore
   @posts=Post.all
 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like= Like.create(user_id: current_user.id, post_id: params[:like][:post_id])
    @post=Post.find(params[:like][:post_id])
    respond_to do |format|
      format.html {}
      format.js
    end


  end

  def destroy
    @like=Like.find(params[:id])
    post_id= @like.post_id
    @post=Post.find(post_id)
    @like.destroy
    respond_to do |format|
      format.html {}
      format.js
    end
  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @hashtag=params[:tag][:hashtag]
    if params[:tag][:hashtag][0]!="#"
      user_search(params[:tag][:hashtag])
    else
      @tag=Tag.find_by(tag_params)
        if @tag
          @posts=@tag.posts
        else
          flash.now[:warning]="No results for #{@hashtag}" if !@tag
        end
    end
  end

  def show
      @tag=Tag.find(params[:id])
      @posts=@tag.posts
      @hashtag=@tag.hashtag
      render "tags/index"
  end


  private
  def tag_params
    params.require(:tag).permit(:hashtag)
  end

  def user_search(name)
    @name=name.capitalize
    count=User.where(first_name: @name).count
    if count === 0
     flash.now[:warning]="We couldn't find a user called #{@name}"
    elsif count === 1
      redirect_to user_path(User.find_by(first_name: @name))
    else
      @users=User.where(first_name: @name)
      redirect_to users_path(:name =>@name)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title="")
    base_title= "Instagram"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    if resource.errors.full_messages.any?
      flash.now[:error] = resource.errors.full_messages.join(' & ')
    end
    return ''
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
  def followed_by_visitor?(followers)
     if followers.include?(current_user)
       return true
     end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
  def liked?(post)
    Like.exists?(post_id: post.id, user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div class="header-box">
    <div class="thirds">
    <%= link_to root_url do %>
      <div class="logo-image">
        <%= image_tag "logo.PNG", class: :gylph %>
      </div>
      <div class="logo-text">
        Insteadgram
      </div>
      <% end %>
    </div>
      <div class="thirds middle">

          <%= render "partials/tag_search" %>

      </div>
      <div class="thirds">
        <div class="glyph-cont">
          <%= link_to image_tag("user.png", class: :gylph), user_path(current_user)  %>
        </div>

        <div class="glyph-cont">
          <%=  link_to image_tag("activity.png", class: :gylph), liked_posts_path  %>
        </div>
        <div class="glyph-cont">
          <%= link_to image_tag("explore.png", class: :gylph), explore_path  %>
        </div>
      </div>

  </div>

</header>
<div id="spacer"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('icon.ico'), :rel => 'icon', :type =>  'image/png' %>
    <meta name="viewport" content="initial-scale = 1.0, maximum-scale = 1.0" />
<title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Satisfy" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "layouts/header" %>
      <% end %>
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_comments.html.erb
<% @comments.each do |comment| %>

  <div class="comments-container">
    <p class="caption_line" id="username"><%= comment.user.username %></p>
    <p class="caption_line"><%= comment.text %></p>
    <% if comment.user === current_user %>
      <%= link_to "Remove", comment_path(comment), method: :delete, class: :caption_line, id: :username, remote: true %>
    <% end %>
  </div>

<% end %>

app/views/partials/_followers.html.erb
<div class="box">
  <h2>Followers</h2>
    <% @followers.each do |follower|  %>
      <%= link_to "#{follower.username}", user_path(follower) %>
    <% end %>
</div>

app/views/partials/_following_form.html.erb
<%= form_for(@user.passive_followings.build, remote: true) do |f| %>
<%= f.hidden_field :followed_id, value: @user.id %>
<%= f.submit "Follow", class: :follow_btn, id: :follow_btn %>
<% end %>

app/views/partials/_hcomment_form.html.erb
<div class="comment-form-container">
  <%= form_for(Comment.new, remote: true) do |f| %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= f.text_field :text, :placeholder => "Add a comment...", class: :comment_field, required: :required %>
  <%= f.submit "Save", class: :hidden %>
  <% end %>
</div>

app/views/partials/_hcomments.html.erb
<% post.comments.each do |comment| %>

<div class="comments-container">

  <p class="caption_line" id="username"><%= comment.user.username %></p>
  <p class="caption_line"><%= comment.text %></p>
  <% if comment.user === current_user %>
    <%= link_to "Remove", comment_path(comment), method: :delete, class: :caption_line, id: :username, remote: true %>
  <% end %>
</div>

<% end %>

app/views/partials/_hdelete_post.html.erb
<div class="">
 <%= form_for((post), html: { method: :delete }) do |f| %>
 <%= f.submit "Delete" %>
 <% end %>
</div>

app/views/partials/_hlike.html.erb
<%= form_for local_assigns[:post].likes.build, remote: true do |f| %>
<%= f.hidden_field :post_id, value: post.id %>
<%= f.submit "Submit", :type => :image, :src => image_path("like.png"), :class=> [:like, :no_val] %>
<% end %>

app/views/partials/_hun_following_form.html.erb
 <%= form_for(user.passive_followings.find_by(follower_id: current_user.id), html: { method: :delete }, remote: true) do |f| %>
 <%= f.submit "Following", class: :follow_btn, id: :follow_btn %>
 <% end %>

app/views/partials/_hunlike.html.erb
<%= form_for(post.likes.find_by(user_id: current_user.id), html: { method: :delete }, remote: true) do |f| %>
<%= f.submit "Unlike", :type => :image, :src => image_path("liked.png"), class: [:like, :no_val] %>
<% end %>

app/views/partials/_post.html.erb
<% @posts.each do |post| %>
<div class="post-container">
  <%= link_to  user_path(post.user) do %>
    <div class="user-info">
      <% if !post.user.avatar.file.nil? %>
          <%= image_tag(post.user.avatar.main.url, class: :user_image) %>
        <% else %>
          <%= image_tag("user.png", class: :user_image) %>
      <% end %>
      <p class="user_name"><%= post.user.username %></p>
    </div>
  <% end %>

  <%= link_to image_tag(post.post_image.main.url, class: :post_image), post_path(post) %>

  <div class="post-info">
    <div id="post_<%= post.id %>">
      <% if liked?(post) %>
        <%= render "partials/hunlike", post: post %>
      <% else %>
        <%= render "partials/hlike", post: post %>
      <% end %>
    </div>

    <p id="likes_<%= post.id %>"><%= pluralize(post.likes.count, "Like") %></p></br>

    <p class="caption_line post-caption" id="username"><%= post.user.username %></p>
    <p class="caption_line"><%= "  #{post.caption}" %></p></br>

    <div id="comments_<%= post.id %>">
      <% if post.comments.length > 0 %>
        <%= render "partials/hcomments", post: post %>
      <% end %>
    </div>

    <div id="comment_form_<%= post.id %>">
      <%= render "partials/hcomment_form", post: post %>
    </div>

  </div>

</div>



<% end %>

app/views/partials/_post_form.html.erb
<div class="form-container">
<%= form_for @post, :html =>{:multipart => true}  do |f| %>
  <div class="actions">
    <%= f.file_field :post_image, required: :required %>
  </div>

  <div class="field">
    <%= f.text_field :caption, :placeholder => 'Title', class: :in_field,  required: :required %>
  </div>

  <div class="field">
    <%= f.fields_for :tags do |tag_form| %>
      <%= tag_form.text_field :hashtag, :placeholder => '#tag...', class: [:in_field, :no_val] %>
    <% end  %>
  </div>
  <div class="actions">
    <%= f.submit "Post ", class: :submit %>
  </div>
  <% end %>
</div>

app/views/partials/_tag_search.html.erb
<%= form_for(Tag.new, method: :get) do |f| %>
  <%= f.text_field :hashtag, :placeholder => '#search', class: :search, required: :required %>
  <%= f.submit "Search", class: :hidden %>
<% end %>

app/views/partials/_tags.html.erb
<p>Tags:</p>
<% @tags.each do |tag| %>
<%= link_to tag.hashtag, tag_path(tag) %>
<% end %>

app/views/partials/_unlike.html.erb
 <%= form_for(@post.likes.find_by(user_id: current_user.id), html: { method: :delete }, remote: true) do |f| %>
 <%= f.submit "Unlike", :type => :image, :src => image_path("liked.png"), :class=> [:like, :no_val] %>
 <% end %>